# Generated by Django 5.2.5 on 2025-10-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Weekday AM–PM default route'", max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Only Mon–Fri will be materialized.')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='scheduler.company')),
            ],
            options={
                'ordering': ['company', 'weekday', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display/materialize order')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('vehicle_name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.TimeField()),
                ('pickup_address', models.CharField(blank=True, max_length=300)),
                ('dropoff_address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.driver')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduler.scheduletemplate')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.vehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduletemplate',
            constraint=models.UniqueConstraint(fields=('company', 'weekday', 'name'), name='uniq_template_name_per_company_weekday'),
        ),
    ]
