# Generated by Django 5.2.5 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_scheduletemplate_scheduletemplateentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplateentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
