# Generated by Django 5.2.5 on 2025-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_alter_client_created_at_alter_client_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="dropoff_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="pickup_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="dropoff_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="pickup_city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
