# Generated by Django 5.2.5 on 2025-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_client_dropoff_city_client_pickup_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletemplateentry",
            name="dropoff_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="scheduletemplateentry",
            name="pickup_city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
