# Generated by Django 5.2.5 on 2025-10-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0010_scheduletemplateentry_dropoff_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduletemplateentry",
            name="client_name",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
