# Generated by Django 5.2.7 on 2025-11-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_scheduletemplateentry_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.client'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
