# Generated by Django 5.2.7 on 2025-11-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_scheduleentry_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('delayed', 'Delayed'), ('incident', 'Incident')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_event_logs', to='scheduler.driver')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='scheduler.scheduleentry')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_event_logs', to='scheduler.vehicle')),
            ],
            options={
                'verbose_name': 'Trip Event Log',
                'verbose_name_plural': 'Trip Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
